#!/usr/bin/env python3
"""Audit Kentucky recap PDFs for the active federal/state office families."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
from collections import Counter, defaultdict
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT_DIR / "data/raw/official/kentucky"
OUTPUT_JSON = ROOT_DIR / "public/results/kentucky-recap-schema-audit.json"
OUTPUT_MD = ROOT_DIR / "docs/sources/kentucky-recap-schema-audit.md"

OFFICE_PATTERNS = (
    ("President", re.compile(r"PRESIDENT.*UNITED STATES", re.I)),
    ("U.S. Senate", re.compile(r"UNITED STATES SENATOR", re.I)),
    ("U.S. House", re.compile(r"UNITED STATES REPRESENTATIVE", re.I)),
    ("Governor", re.compile(r"GOVERNOR", re.I)),
    ("State Senate", re.compile(r"STATE SENATOR", re.I)),
    ("State House", re.compile(r"STATE REPRESENTATIVE", re.I)),
)


def extract_text(path: Path) -> str:
    result = subprocess.run(
        ["pdftotext", "-layout", str(path), "-"],
        check=True,
        capture_output=True,
        text=True,
        errors="replace",
    )
    return result.stdout


def offices_in_text(text: str) -> set[str]:
    offices = set()
    pending = None
    for line in text.splitlines():
        normalized = re.sub(r"\s+", " ", line.strip())
        heading = next((office for office, pattern in OFFICE_PATTERNS if pattern.search(normalized)), None)
        if heading:
            pending = heading
            if "VOTE FOR" in normalized.upper():
                offices.add(heading)
                pending = None
            continue
        if pending and normalized.upper().startswith("VOTE FOR"):
            offices.add(pending)
            pending = None
    return offices


def build_audit() -> dict:
    rows = []
    for path in sorted(RAW_DIR.glob("20*_*.pdf")):
        match = re.match(r"(20\d{2})_", path.name)
        if not match:
            continue
        text = extract_text(path)
        offices = sorted(offices_in_text(text))
        normalized = re.sub(r"\s+", " ", text).strip()
        mail_in_only = bool(re.search(r"TOTAL\s+Mail In\s*$", text, re.I | re.M)) and not bool(
            re.search(r"Absentee|Early Voting|Election Day", text, re.I)
        )
        rows.append(
            {
                "year": int(match.group(1)),
                "file": str(path.relative_to(ROOT_DIR)),
                "offices": offices,
                "content_status": "blank" if not normalized else "mail_in_only" if mail_in_only else "usable",
                "text_characters": len(normalized),
            }
        )
    by_year = defaultdict(list)
    for row in rows:
        by_year[row["year"]].append(row)
    summary = {}
    for year, year_rows in sorted(by_year.items()):
        summary[str(year)] = {
            "files": len(year_rows),
            "office_file_counts": dict(Counter(office for row in year_rows for office in row["offices"])),
            "content_status_counts": dict(Counter(row["content_status"] for row in year_rows)),
            "blank_files": [row["file"] for row in year_rows if row["content_status"] == "blank"],
            "mail_in_only_files": [row["file"] for row in year_rows if row["content_status"] == "mail_in_only"],
        }
    return {"state_po": "KY", "rows": rows, "summary": summary}


def markdown(audit: dict) -> str:
    lines = [
        "# Kentucky Recap Schema Audit",
        "",
        "Generated by `npm run kentucky:recaps:audit`.",
        "",
        "This audit checks which active federal/state office headings are present in each staged official county recap PDF. It does not publish normalized results.",
        "",
        "| Year | Files audited | Usable | Mail-in only | Blank | President | U.S. Senate | U.S. House | Governor | State Senate | State House |",
        "| ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    offices = [office for office, _ in OFFICE_PATTERNS]
    for year, summary in audit["summary"].items():
        counts = summary["office_file_counts"]
        statuses = summary["content_status_counts"]
        lines.append(
            "| "
            + " | ".join(
                [year, str(summary["files"]), str(statuses.get("usable", 0)), str(statuses.get("mail_in_only", 0)), str(statuses.get("blank", 0))]
                + [str(counts.get(office, 0)) for office in offices]
            )
            + " |"
        )
        if summary["blank_files"]:
            lines.append(f"- Blank files: {', '.join(summary['blank_files'])}")
        if summary["mail_in_only_files"]:
            lines.append(f"- Mail-in-only files: {', '.join(summary['mail_in_only_files'])}")
    lines.extend(["", "The parser must aggregate repeated precinct sections within each county report before contest reconciliation. Blank and mail-in-only files are not sufficient evidence for a complete county total.", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    audit = build_audit()
    if args.check:
        if not audit["rows"]:
            raise SystemExit("No Kentucky recap PDFs found")
        print(f"Kentucky recap schema checks passed for {len(audit['rows'])} files.")
        return 0
    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps(audit, indent=2) + "\n", encoding="utf-8")
    OUTPUT_MD.write_text(markdown(audit), encoding="utf-8")
    print(f"Wrote {OUTPUT_JSON.relative_to(ROOT_DIR)} and {OUTPUT_MD.relative_to(ROOT_DIR)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
