#!/usr/bin/env python3
"""Audit locally staged files for the first structured legacy lanes."""

from __future__ import annotations

import csv
import json
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
RAW_ROOT = ROOT_DIR / "data/raw/official"
OUTPUT_PATH = ROOT_DIR / "public/results/legacy-acquisition-audit.json"
DOC_PATH = ROOT_DIR / "docs/sources/legacy-acquisition-audit.md"


def audit(path: Path) -> dict:
    raw = path.read_bytes()
    text = raw.decode("utf-8", errors="replace")
    suffix = path.suffix.lower()
    status = "usable"
    format_name = suffix.lstrip(".")
    rows = None
    if "Request Rejected" in text or "support ID" in text:
        status = "rejected_page"
    elif suffix == ".csv":
        format_name = "csv-precinct-results"
        rows = max(0, text.count("\n") - 1)
        try:
            with path.open(newline="", encoding="utf-8") as handle:
                header = next(csv.reader(handle))
            if "VoteCount" not in header or "ContestName" not in header:
                status = "unexpected_schema"
        except (OSError, StopIteration):
            status = "unreadable"
    elif suffix == ".txt":
        format_name = "delaware-semicolon-results"
        rows = text.count("\n")
        if not text.lstrip().startswith(("General Election", "State of Delaware")):
            status = "unexpected_schema"
    elif suffix == ".html":
        format_name = "idaho-official-html"
        title = ""
        if "<title>" in text.lower():
            title = text.lower().split("<title>", 1)[1].split("</title>", 1)[0].strip()
        if title != "statewide totals" or "Voting Statistics" not in text:
            status = "unexpected_schema"
    return {
        "path": str(path.relative_to(ROOT_DIR)),
        "bytes": len(raw),
        "format": format_name,
        "rows_or_lines": rows,
        "status": status,
    }


def build_report() -> dict:
    files = []
    for state in ("delaware", "idaho", "illinois", "colorado"):
        root = RAW_ROOT / state / "legacy"
        files.extend(audit(path) for path in sorted(root.glob("*") if root.exists() else []))
    return {
        "cohort": "legacy-cohort-01",
        "scope": "2010-2018 and 2000-2008",
        "files": files,
        "summary": {
            "staged": len(files),
            "usable": sum(item["status"] == "usable" for item in files),
            "rejected_or_invalid": sum(item["status"] != "usable" for item in files),
        },
    }


def markdown(report: dict) -> str:
    lines = [
        "# Legacy Acquisition Audit",
        "",
        "Generated by `npm run legacy:acquisition:audit`.",
        "",
        "These are staged official files, not imported contest data. A file must pass this audit and an office-aware parser before its registry status can become `imported`.",
        "",
        "| File | Format | Size | Rows/lines | Status |",
        "| --- | --- | ---: | ---: | --- |",
    ]
    for item in report["files"]:
        lines.append(f"| `{item['path']}` | {item['format']} | {item['bytes']} | {item['rows_or_lines'] or '-'} | `{item['status']}` |")
    lines.extend(
        [
            "",
            f"Staged files: `{report['summary']['staged']}`; usable: `{report['summary']['usable']}`; rejected or invalid: `{report['summary']['rejected_or_invalid']}`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    report = build_report()
    OUTPUT_PATH.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    DOC_PATH.write_text(markdown(report), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT_DIR)} and {DOC_PATH.relative_to(ROOT_DIR)}.")
    print(report["summary"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
