#!/usr/bin/env python3
"""Audit staged Idaho legacy HTML files before parser work begins."""

from __future__ import annotations

import json
import re
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parents[1]
RAW_DIR = ROOT_DIR / "data/raw/official/idaho/legacy"
OUTPUT_PATH = ROOT_DIR / "public/results/idaho-legacy-source-audit.json"
DOC_PATH = ROOT_DIR / "docs/sources/idaho-legacy-audit.md"
YEAR_RE = re.compile(r"idaho_(\d{4})_general_statewide_totals\.html$")


def audit_file(path: Path) -> dict:
    text = path.read_text(encoding="utf-8", errors="replace")
    title_match = re.search(r"<title>\s*(.*?)\s*</title>", text, re.I | re.S)
    title = re.sub(r"\s+", " ", title_match.group(1)).strip() if title_match else ""
    year_match = YEAR_RE.search(path.name)
    result_page = title == "Statewide Totals" and "Statewide Totals" in text
    return {
        "year": int(year_match.group(1)) if year_match else None,
        "path": str(path.relative_to(ROOT_DIR)),
        "title": title,
        "bytes": path.stat().st_size,
        "result_page": result_page,
        "status": "ready_for_parser" if result_page else "portal_or_invalid",
    }


def build_report() -> dict:
    files = sorted(RAW_DIR.glob("idaho_*_general_statewide_totals.html"))
    rows = [audit_file(path) for path in files]
    return {
        "state_po": "ID",
        "source": "Idaho Secretary of State official election archive",
        "source_url": "https://archive.sos.idaho.gov/ELECT/results/index.html",
        "files": rows,
        "ready_years": [row["year"] for row in rows if row["result_page"]],
        "invalid_years": [row["year"] for row in rows if not row["result_page"]],
    }


def markdown(report: dict) -> str:
    lines = [
        "# Idaho Legacy Source Audit",
        "",
        "Generated by `npm run legacy:idaho:audit`.",
        "",
        "The archive has multiple URL generations. Portal shells are retained as audit evidence but are rejected as result files.",
        "",
        "| Year | Bytes | Title | Status |",
        "| ---: | ---: | --- | --- |",
    ]
    for row in report["files"]:
        lines.append(f"| {row['year']} | {row['bytes']} | {row['title']} | `{row['status']}` |")
    lines.extend(
        [
            "",
            f"Ready for parser work: `{', '.join(map(str, report['ready_years'])) or 'none'}`.",
            f"Rejected portal/invalid files: `{', '.join(map(str, report['invalid_years'])) or 'none'}`.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    report = build_report()
    OUTPUT_PATH.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    DOC_PATH.write_text(markdown(report), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT_DIR)} and {DOC_PATH.relative_to(ROOT_DIR)}.")
    print(f"Ready years: {report['ready_years']}; rejected years: {report['invalid_years']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
