#!/usr/bin/env python3
"""Generate the federal/state election coverage matrix for all 50 states."""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[1]
REGISTRY_DIR = ROOT_DIR / "data/source-registry"
RESULTS_PATH = ROOT_DIR / "public/results/county-presidential-summary.json"
OUTPUT_PATH = ROOT_DIR / "public/results/national-coverage-matrix.json"
REPORT_PATH = ROOT_DIR / "docs/national-coverage-report.md"
YEARS = list(range(2000, 2028, 2))
OFFICES = ["President", "U.S. Senate", "U.S. House", "Governor", "State Senate", "State House"]
STATES = {
    "AL": "Alabama", "AK": "Alaska", "AZ": "Arizona", "AR": "Arkansas", "CA": "California", "CO": "Colorado",
    "CT": "Connecticut", "DE": "Delaware", "FL": "Florida", "GA": "Georgia", "HI": "Hawaii", "ID": "Idaho",
    "IL": "Illinois", "IN": "Indiana", "IA": "Iowa", "KS": "Kansas", "KY": "Kentucky", "LA": "Louisiana",
    "ME": "Maine", "MD": "Maryland", "MA": "Massachusetts", "MI": "Michigan", "MN": "Minnesota", "MS": "Mississippi",
    "MO": "Missouri", "MT": "Montana", "NE": "Nebraska", "NV": "Nevada", "NH": "New Hampshire", "NJ": "New Jersey",
    "NM": "New Mexico", "NY": "New York", "NC": "North Carolina", "ND": "North Dakota", "OH": "Ohio", "OK": "Oklahoma",
    "OR": "Oregon", "PA": "Pennsylvania", "RI": "Rhode Island", "SC": "South Carolina", "SD": "South Dakota",
    "TN": "Tennessee", "TX": "Texas", "UT": "Utah", "VT": "Vermont", "VA": "Virginia", "WA": "Washington",
    "WV": "West Virginia", "WI": "Wisconsin", "WY": "Wyoming",
}


def load_registry() -> list[dict[str, Any]]:
    entries = []
    for path in sorted(REGISTRY_DIR.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        entries.extend(entry | {"state_po": data["state_po"]} for entry in data["entries"] if entry["scope"] != "mayor")
    return entries


def presidential_states() -> set[str]:
    summary = json.loads(RESULTS_PATH.read_text(encoding="utf-8"))
    return {county["state_po"] for county in summary["counties"]}


def status_for(state_po: str, year: int, office: str, entries: list[dict[str, Any]], president_states: set[str]) -> str:
    matching = [entry for entry in entries if entry["state_po"] == state_po and office in entry["offices"] and year in entry["years"]]
    if matching and any(entry.get("not_on_even_year_ballot") for entry in matching):
        return "not_on_ballot"
    if any(entry["status"] == "imported" for entry in matching):
        return "imported"
    if matching and any(entry["status"] == "source_identified" for entry in matching):
        return "source_identified"
    if matching and any(entry["status"] == "blocked" for entry in matching):
        return "blocked"
    if year == 2026:
        return "not_yet_available"
    if office == "President" and year <= 2024 and state_po in president_states:
        return "imported"
    return "needs_discovery"


def markdown(matrix: dict[str, Any]) -> str:
    cells = matrix["cells"]
    counts = Counter(cell["status"] for cell in cells)
    lines = [
        "# National Federal/State Coverage Report", "", "Generated by `npm run coverage:national`.", "",
        "The matrix covers all 50 states, even-year general elections from 2000 through 2026, and federal/state offices only.", "",
        "## Summary", "", 
    ]
    for status in ("imported", "source_identified", "needs_discovery", "blocked", "not_on_ballot", "not_yet_available"):
        lines.append(f"- `{status}`: {counts[status]} cells")
    lines.extend(["", "## State Progress", "", "| State | Imported | Source identified | Discovery needed | Blocked | Not on ballot | Not yet available |", "| --- | ---: | ---: | ---: | ---: | ---: | ---: |"])
    for state in STATES:
        state_cells = [cell for cell in cells if cell["state_po"] == state]
        state_counts = Counter(cell["status"] for cell in state_cells)
        lines.append(f"| {state} | {state_counts['imported']} | {state_counts['source_identified']} | {state_counts['needs_discovery']} | {state_counts['blocked']} | {state_counts['not_on_ballot']} | {state_counts['not_yet_available']} |")
    lines.extend(["", "## Batch Rule", "", "A state/year batch is publishable only when its source, parser, normalized rows, reconciliation tests, and coverage status are present. `source_identified` and `needs_discovery` cells remain out of the map-ready dataset.", ""])
    return "\n".join(lines)


def main() -> None:
    entries = load_registry()
    president_state_pos = presidential_states()
    cells = [
        {
            "state_po": state_po,
            "state": state_name,
            "year": year,
            "office": office,
            "election_type": "general",
            "status": status_for(state_po, year, office, entries, president_state_pos),
        }
        for state_po, state_name in STATES.items()
        for year in YEARS
        for office in OFFICES
    ]
    matrix = {"scope": {"states": list(STATES), "years": YEARS, "offices": OFFICES, "election_type": "general"}, "cells": cells}
    OUTPUT_PATH.write_text(json.dumps(matrix, separators=(",", ":")), encoding="utf-8")
    REPORT_PATH.write_text(markdown(matrix), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT_DIR)} and {REPORT_PATH.relative_to(ROOT_DIR)} with {len(cells)} cells.")


if __name__ == "__main__":
    main()
