#!/usr/bin/env python3
"""Validate the source registry and write a bulk-backfill report."""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any


ROOT_DIR = Path(__file__).resolve().parents[1]
REGISTRY_DIR = ROOT_DIR / "data/source-registry"
REPORT_PATH = ROOT_DIR / "docs/source-registry-report.md"

STATUSES = {"imported", "source_identified", "needs_discovery", "blocked"}
SCOPES = {"statewide", "district", "geometry", "mayor", "precinct"}
PILOT_STATE_ORDER = ["FL", "CA", "PA", "TX", "OH"]


class RegistryFailure(Exception):
    pass


def require(condition: bool, message: str) -> None:
    if not condition:
        raise RegistryFailure(message)


def load_state_file(path: Path) -> dict[str, Any]:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise RegistryFailure(f"{path.relative_to(ROOT_DIR)} is invalid JSON: {exc}") from exc
    require(isinstance(data, dict), f"{path.relative_to(ROOT_DIR)} must contain an object")
    require(isinstance(data.get("state"), str) and data["state"], f"{path.name} state is required")
    require(isinstance(data.get("state_po"), str) and len(data["state_po"]) == 2, f"{path.name} state_po must be two letters")
    entries = data.get("entries")
    require(isinstance(entries, list) and entries, f"{path.name} entries must be a non-empty list")
    for index, entry in enumerate(entries):
        validate_entry(entry, data["state_po"], f"{path.name}.entries[{index}]")
    return data


def validate_entry(entry: Any, state_po: str, label: str) -> None:
    require(isinstance(entry, dict), f"{label} must be an object")
    require(isinstance(entry.get("id"), str) and entry["id"], f"{label}.id is required")
    require(entry.get("scope") in SCOPES, f"{label}.scope must be one of {sorted(SCOPES)}")
    offices = entry.get("offices")
    require(isinstance(offices, list) and all(isinstance(office, str) and office for office in offices), f"{label}.offices must be non-empty strings")
    years = entry.get("years")
    require(isinstance(years, list) and all(isinstance(year, int) for year in years), f"{label}.years must be integer list")
    require(years == sorted(set(years)), f"{label}.years must be unique and sorted")
    require(entry.get("status") in STATUSES, f"{label}.status must be one of {sorted(STATUSES)}")
    require(isinstance(entry.get("format"), str) and entry["format"], f"{label}.format is required")
    require(isinstance(entry.get("geography"), str) and entry["geography"], f"{label}.geography is required")
    urls = entry.get("urls")
    require(isinstance(urls, list) and urls, f"{label}.urls must be a non-empty list")
    require(all(isinstance(url, str) and url.startswith("https://") for url in urls), f"{label}.urls must be https URLs")
    require(isinstance(entry.get("parser"), str) and entry["parser"], f"{label}.parser is required")
    if entry["status"] == "imported":
        require(entry.get("quality_grade") in {"A", "B", "C", "D"}, f"{label}.quality_grade is required for imported entries")
        require(not entry["parser"].startswith("planned:"), f"{label}.parser cannot be planned for imported entries")
    if state_po == "FL":
        require(entry["id"].startswith("fl-"), f"{label}.id should start with fl-")


def load_registry() -> list[dict[str, Any]]:
    states = []
    for path in sorted(REGISTRY_DIR.glob("*.json")):
        states.append(load_state_file(path))
    state_pos = {state["state_po"] for state in states}
    require(set(PILOT_STATE_ORDER) <= state_pos, f"registry must include pilot states {PILOT_STATE_ORDER}")
    ids: set[str] = set()
    for state in states:
        for entry in state["entries"]:
            require(entry["id"] not in ids, f"duplicate source id: {entry['id']}")
            ids.add(entry["id"])
    return sorted(states, key=lambda state: PILOT_STATE_ORDER.index(state["state_po"]) if state["state_po"] in PILOT_STATE_ORDER else 99)


def entry_year_label(entry: dict[str, Any]) -> str:
    years = entry["years"]
    if not years:
        return "unscoped"
    if len(years) > 2 and years == list(range(years[0], years[-1] + 1, 2)):
        return f"{years[0]}-{years[-1]}"
    return ", ".join(str(year) for year in years)


def report_markdown(states: list[dict[str, Any]]) -> str:
    all_entries = [entry | {"state": state["state"], "state_po": state["state_po"]} for state in states for entry in state["entries"]]
    status_counts = Counter(entry["status"] for entry in all_entries)
    format_backlog = defaultdict(list)
    for entry in all_entries:
        if entry["status"] != "imported":
            format_backlog[entry["format"]].append(entry)

    lines = [
        "# Source Registry Report",
        "",
        "Generated by `npm run sources:report`.",
        "",
        "## Summary",
        "",
        f"- States tracked: {', '.join(state['state_po'] for state in states)}",
        f"- Registry entries: {len(all_entries)}",
        f"- Imported entries: {status_counts['imported']}",
        f"- Source identified: {status_counts['source_identified']}",
        f"- Needs discovery: {status_counts['needs_discovery']}",
        f"- Blocked: {status_counts['blocked']}",
        "",
        "## State Coverage",
        "",
        "| State | Imported | Identified | Needs discovery | Main open lanes |",
        "| --- | ---: | ---: | ---: | --- |",
    ]

    for state in states:
        entries = state["entries"]
        counts = Counter(entry["status"] for entry in entries)
        open_lanes = sorted({entry["format"] for entry in entries if entry["status"] != "imported"})
        lines.append(
            f"| {state['state_po']} | {counts['imported']} | {counts['source_identified']} | {counts['needs_discovery']} | {', '.join(open_lanes) or 'none'} |"
        )

    lines.extend(
        [
            "",
            "## Backlog By Parser Family",
            "",
        ]
    )
    for source_format in sorted(format_backlog):
        entries = sorted(format_backlog[source_format], key=lambda item: (item["state_po"], item["id"]))
        lines.append(f"### `{source_format}`")
        lines.append("")
        for entry in entries:
            offices = ", ".join(entry["offices"])
            lines.append(
                f"- `{entry['id']}`: {entry['state_po']} {entry['scope']} ({offices}), years {entry_year_label(entry)}, status `{entry['status']}`."
            )
        lines.append("")

    lines.extend(
        [
            "## Recommended Bulk Lanes",
            "",
            "1. `current-results-html`: parse reachable public current-results pages where they provide useful statewide totals.",
            "2. `state-portal-mixed`: import official TX/OH files after they are downloaded through a browser/session or otherwise supplied under `data/raw/`.",
            "3. `mixed-county-city-archives`: backfill additional mayor years where structured official archives are available, then extend the parser family to PA/TX/OH/CA mayor archives.",
            "4. `mixed-geometry`: identify precinct geometry sources separately because boundaries and file sizes may require a different storage strategy.",
            "",
            "## Imported Entries",
            "",
        ]
    )
    for entry in sorted((entry for entry in all_entries if entry["status"] == "imported"), key=lambda item: item["id"]):
        lines.append(f"- `{entry['id']}`: {entry['state_po']} {entry['scope']}, years {entry_year_label(entry)}, parser `{entry['parser']}`.")

    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Validate only; do not write the report.")
    parser.add_argument("--output", type=Path, default=REPORT_PATH, help="Markdown report path.")
    args = parser.parse_args()

    states = load_registry()
    if args.check:
        print(f"Source registry checks passed for {sum(len(state['entries']) for state in states)} entries.")
        return 0

    output = args.output if args.output.is_absolute() else ROOT_DIR / args.output
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report_markdown(states), encoding="utf-8")
    print(f"Wrote {output.relative_to(ROOT_DIR)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
