#!/usr/bin/env python3
"""Report raw-source availability for the active national cohort."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT_DIR = Path(__file__).resolve().parents[1]
COHORT_PATH = ROOT_DIR / "data/national-cohorts/cohort-01-2020-2024.json"
OUTPUT_JSON = ROOT_DIR / "public/results/national-cohort-01-preflight.json"
OUTPUT_MD = ROOT_DIR / "docs/national-cohort-01-preflight.md"


def load_cohort() -> dict[str, Any]:
    return json.loads(COHORT_PATH.read_text(encoding="utf-8"))


def raw_files(state_po: str, year: int) -> list[str]:
    state_dir = {
        "GA": "georgia",
        "KY": "kentucky",
        "NC": "north-carolina",
        "VA": "virginia",
        "WI": "wisconsin",
    }.get(state_po, state_po.lower())
    root = ROOT_DIR / "data/raw/official" / state_dir
    if not root.exists():
        return []
    return sorted(
        str(path.relative_to(ROOT_DIR))
        for path in root.rglob("*")
        if path.is_file() and str(year) in path.name
    )


def build_report() -> dict[str, Any]:
    cohort = load_cohort()
    rows = []
    for state in cohort["states"]:
        for year in cohort["years"]:
            files = raw_files(state["state_po"], year)
            rows.append(
                {
                    "state_po": state["state_po"],
                    "year": year,
                    "raw_file_count": len(files),
                    "raw_files": files,
                    "status": "files_present" if files else "needs_source",
                }
            )
    return {
        "cohort_id": cohort["id"],
        "scope": cohort["scope"],
        "offices": cohort["offices"],
        "rows": rows,
        "summary": {
            "state_year_batches": len(rows),
            "files_present": sum(row["status"] == "files_present" for row in rows),
            "needs_source": sum(row["status"] == "needs_source" for row in rows),
        },
    }


def markdown(report: dict[str, Any]) -> str:
    lines = [
        "# National Cohort 01 Preflight",
        "",
        "Generated by `npm run national:cohort:preflight`.",
        "",
        "This is a raw-file availability check. A present file is not considered imported until it has an office-aware parser, reconciliation, and generated output.",
        "",
        f"- State/year batches: {report['summary']['state_year_batches']}",
        f"- Batches with raw files: {report['summary']['files_present']}",
        f"- Batches needing source retrieval: {report['summary']['needs_source']}",
        "",
        "| State | Year | Raw files | Status |",
        "| --- | ---: | ---: | --- |",
    ]
    for row in report["rows"]:
        lines.append(
            f"| {row['state_po']} | {row['year']} | {row['raw_file_count']} | `{row['status']}` |"
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "The current cohort has presidential source files for selected state/year batches. The remaining five office families still require office-specific source files and parsers even where a raw presidential file is present.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    report = build_report()
    if args.check:
        if report["summary"]["state_year_batches"] != 30:
            raise SystemExit("Cohort 01 must contain 30 state/year batches")
        print("National cohort preflight checks passed.")
        return 0
    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    OUTPUT_MD.write_text(markdown(report), encoding="utf-8")
    print(f"Wrote {OUTPUT_JSON.relative_to(ROOT_DIR)} and {OUTPUT_MD.relative_to(ROOT_DIR)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
