#!/usr/bin/env python3
"""Report raw-source availability for the active national cohort."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

ROOT_DIR = Path(__file__).resolve().parents[1]
COHORT_PATH = ROOT_DIR / "data/national-cohorts/cohort-01-2020-2024.json"
OUTPUT_JSON = ROOT_DIR / "public/results/national-cohort-01-preflight.json"
OUTPUT_MD = ROOT_DIR / "docs/national-cohort-01-preflight.md"


def load_cohort() -> dict[str, Any]:
    return json.loads(COHORT_PATH.read_text(encoding="utf-8"))


def raw_files(state_po: str, year: int) -> list[str]:
    state_dir = {
        "GA": "georgia",
        "KY": "kentucky",
        "NC": "north-carolina",
        "VA": "virginia",
        "WI": "wisconsin",
    }.get(state_po, state_po.lower())
    root = ROOT_DIR / "data/raw/official" / state_dir
    if not root.exists():
        return []
    return sorted(
        str(path.relative_to(ROOT_DIR))
        for path in root.rglob("*")
        if path.is_file() and str(year) in path.name
    )


def generated_files(state_po: str, year: int) -> list[str]:
    """Return generated official artifacts that contain the requested year.

    Several importers intentionally use one multi-year summary filename, so
    raw filename matching alone under-reports completed state/year work.
    """
    candidates = {
        "FL": [ROOT_DIR / f"public/results/florida-{year}-statewide-summary.json"],
        "GA": [ROOT_DIR / f"public/results/georgia-{year}-official-contests.json"],
        "WI": [ROOT_DIR / "public/results/county-presidential-summary.json"],
        "CA": [ROOT_DIR / "public/results/california-statewide-summary.json"],
        "KY": [ROOT_DIR / "public/results/kentucky-statewide-summary.json"],
        "NC": [ROOT_DIR / "public/results/north-carolina-statewide-summary.json"],
        "OH": [ROOT_DIR / "public/results/ohio-statewide-summary.json"],
        "PA": [ROOT_DIR / "public/results/pennsylvania-statewide-summary.json"],
        "TX": [ROOT_DIR / "public/results/texas-statewide-summary.json"],
        "VA": [ROOT_DIR / "public/results/virginia-statewide-summary.json"],
    }.get(state_po, [])
    matches = []
    for path in candidates:
        if not path.exists():
            continue
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        elections = data.get("elections", [])
        if any(
            election.get("election", {}).get("year") == year
            or election.get("year") == year
            for election in elections
        ) or (state_po == "WI" and year == 2024):
            matches.append(str(path.relative_to(ROOT_DIR)))
    return sorted(set(matches))


def build_report() -> dict[str, Any]:
    cohort = load_cohort()
    rows = []
    for state in cohort["states"]:
        for year in cohort["years"]:
            files = raw_files(state["state_po"], year)
            outputs = generated_files(state["state_po"], year)
            rows.append(
                {
                    "state_po": state["state_po"],
                    "year": year,
                    "raw_file_count": len(files),
                    "raw_files": files,
                    "generated_file_count": len(outputs),
                    "generated_files": outputs,
                    "status": "files_present" if files else "artifact_present" if outputs else "needs_source",
                }
            )
    return {
        "cohort_id": cohort["id"],
        "scope": cohort["scope"],
        "offices": cohort["offices"],
        "rows": rows,
        "summary": {
            "state_year_batches": len(rows),
            "files_present": sum(row["status"] == "files_present" for row in rows),
            "artifact_present": sum(row["status"] == "artifact_present" for row in rows),
            "needs_source": sum(row["status"] == "needs_source" for row in rows),
        },
    }


def markdown(report: dict[str, Any]) -> str:
    lines = [
        "# National Cohort 01 Preflight",
        "",
        "Generated by `npm run national:cohort:preflight`.",
        "",
        "This is a source and artifact availability check. A raw file is not considered imported until it has an office-aware parser, reconciliation, and generated output. `artifact_present` means an output exists but the raw filename convention did not identify a matching source file.",
        "",
        f"- State/year batches: {report['summary']['state_year_batches']}",
        f"- Batches with raw files: {report['summary']['files_present']}",
        f"- Batches with generated artifacts but no matching raw filename: {report['summary']['artifact_present']}",
        f"- Batches needing source retrieval: {report['summary']['needs_source']}",
        "",
        "| State | Year | Raw files | Generated artifacts | Status |",
        "| --- | ---: | ---: | ---: | --- |",
    ]
    for row in report["rows"]:
        lines.append(
            f"| {row['state_po']} | {row['year']} | {row['raw_file_count']} | {row['generated_file_count']} | `{row['status']}` |"
        )
    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "A present source or generated artifact is not itself proof of complete coverage. Each office still requires an office-aware parser, reconciliation, and registry entry; this report only prevents generic filenames from hiding work that already produced an artifact.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    report = build_report()
    if args.check:
        if report["summary"]["state_year_batches"] != 30:
            raise SystemExit("Cohort 01 must contain 30 state/year batches")
        print("National cohort preflight checks passed.")
        return 0
    OUTPUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_JSON.write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    OUTPUT_MD.write_text(markdown(report), encoding="utf-8")
    print(f"Wrote {OUTPUT_JSON.relative_to(ROOT_DIR)} and {OUTPUT_MD.relative_to(ROOT_DIR)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
