#!/usr/bin/env python3
"""Report explicit source-backed progress for the 2010-2018 and 2000-2008 waves."""

from __future__ import annotations

import argparse
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

from generate_national_coverage_matrix import OFFICES, STATES


ROOT_DIR = Path(__file__).resolve().parents[1]
INVENTORIES = [
    ROOT_DIR / "data/national-cohorts/legacy-2010-2018.json",
    ROOT_DIR / "data/national-cohorts/legacy-2000-2008.json",
]
REGISTRY_DIR = ROOT_DIR / "data/source-registry"
OUTPUT_PATH = ROOT_DIR / "public/results/legacy-wave-status.json"
REPORT_PATH = ROOT_DIR / "docs/legacy-wave-status.md"


def load_entries() -> list[dict[str, Any]]:
    entries = []
    for path in REGISTRY_DIR.glob("*.json"):
        data = json.loads(path.read_text(encoding="utf-8"))
        entries.extend(entry | {"state_po": data["state_po"]} for entry in data["entries"] if entry.get("scope") != "mayor")
    return entries


def status_for(state: str, year: int, office: str, entries: list[dict[str, Any]]) -> str:
    matches = [entry for entry in entries if entry["state_po"] == state and office in entry.get("offices", []) and year in entry.get("years", [])]
    if matches and any(entry.get("not_on_even_year_ballot") for entry in matches):
        return "not_on_ballot"
    if matches and any(entry.get("status") == "imported" for entry in matches):
        return "imported"
    if matches and any(entry.get("status") == "source_identified" for entry in matches):
        return "source_identified"
    return "needs_discovery"


def build_status() -> dict[str, Any]:
    entries = load_entries()
    waves = []
    for inventory_path in INVENTORIES:
        inventory = json.loads(inventory_path.read_text(encoding="utf-8"))
        cells = [
            {"state_po": state, "year": year, "office": office, "status": status_for(state, year, office, entries)}
            for state in inventory["states"] for year in inventory["years"] for office in inventory["offices"]
        ]
        waves.append({"wave": inventory["wave"], "years": inventory["years"], "cell_count": len(cells), "status_counts": dict(Counter(cell["status"] for cell in cells)), "cells": cells})
    return {"generated_by": "scripts/report_legacy_wave_status.py", "waves": waves}


def markdown(status: dict[str, Any]) -> str:
    lines = ["# Legacy Wave Status", "", "Generated by `npm run legacy:status`.", "", "The report measures explicit source-registry coverage for the 2010-2018 and 2000-2008 waves. Presidential rows supplied by the baseline county file are not counted as explicit legacy source imports.", "", "| Wave | Cells | Imported | Source identified | Needs discovery | Not on ballot |", "| --- | ---: | ---: | ---: | ---: | ---: |"]
    for wave in status["waves"]:
        counts = wave["status_counts"]
        lines.append(f"| {wave['wave']} | {wave['cell_count']} | {counts.get('imported', 0)} | {counts.get('source_identified', 0)} | {counts.get('needs_discovery', 0)} | {counts.get('not_on_ballot', 0)} |")
        queued = [cell for cell in wave["cells"] if cell["status"] == "needs_discovery"]
        by_year = Counter(cell["year"] for cell in queued)
        lines.append(f"| Queue by year |  |  |  | {', '.join(f'{year}: {by_year[year]}' for year in sorted(by_year))} |  |")
    lines.extend(["", "## Processing Order", "", "1. Complete explicit 2010-2018 official lanes already present in the registry, starting with states that have structured archives.", "2. Add official source records and parsers in ten-state cohorts; do not mark a lane imported from a presidential baseline alone.", "3. Start 2000-2008 with official legacy archives and scanned canvass books, assigning quality grade B for official OCR and C only for cited compiled references.", "4. Re-run the full project checks after each cohort and preserve historical district-cycle metadata.", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    status = build_status()
    if args.check:
        expected = {"2010-2018": 1500, "2000-2008": 1500}
        actual = {wave["wave"]: wave["cell_count"] for wave in status["waves"]}
        if actual != expected:
            raise SystemExit(f"legacy wave dimensions mismatch: {actual}")
        print("Legacy wave inventory checks passed.")
        return 0
    OUTPUT_PATH.write_text(json.dumps(status, separators=(",", ":")), encoding="utf-8")
    REPORT_PATH.write_text(markdown(status), encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT_DIR)} and {REPORT_PATH.relative_to(ROOT_DIR)}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
